### ISSUE TITLE
Can't build example program

### ISSUE THREAD

**Issue by emk** [jwilm/chatbot#14]
Looks like a great project!

Building the example program on the front page from both the cargo package and from git, I get:

```
   Compiling statbot v0.1.0 (file:///home/emk/w/clients/faraday/statbot)
src/main.rs:6:5: 6:42 error: unresolved import `chatbot::handler::BasicMessageHandler`. There is no `BasicMessageHandler` in `chatbot::handler`
src/main.rs:6 use chatbot::handler::BasicMessageHandler;
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

It might be worth putting a copy of the example program in `examples/`, so that Cargo automatically builds it before publishing.

**Comment by jwilm** [comment]
Oh nuts, the example in the README is slightly out of date. If only cargo would compile that code as well...

I like you suggestion for the examples - will get on that shortly. In the mean time, you could copy the [example in the docs](http://chatbot.rs/chatbot/#examples) since that one is tested by cargo and should work.

**Comment by jwilm** [comment]
I updated the README as well with a correct example. Thanks for pointing this out! :smile:

**Comment by emk** [comment]
No problem! Going to try this out soon. :-)
